### PR TITLE
Move nf-core-modified out of local for better visual hierarchy

### PR DESCRIPTION
**Pull request by mertcelebi**
Feel free to reject this change. We made this change for the phylorthology pipeline and I think it makes things a little bit clearer.

### CODE REVIEW

**Comment by mertcelebi** [comment]
ugh, `nf-core lint` fails... i am sure there's a way to fix that, but I'll only do it if you think this change is worthwhile.

**Comment by taylorreiter** [comment]
i like the organization/better visibility if it passes the linter!

**Comment by elizabethmcd** [comment]
I previously tried an organizational change like this and not only will it fail the linter, but if you try to add modules with `nf-core modules install <MODULE>` later on it will fail because it doesn't recognize the `nf-core-modified` directory in the `modules` directory, so I put it back into `local`.

**Comment by taylorreiter** [comment]
Ah that's great insight Elizabeth. I suggest we abandon ship and leave it as it is now then.

**Comment by mertcelebi** [comment]
Closing since we should probably use `nf-core modules patch` for this stuff.

**Pull request closed without merging**
